{
 "title": "sockstat_exporter",
 "description": "sockstat exporter test",
 "tags": [ "sockstat" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "TCP sent queue",
   "type": "timeseries",
   "description": "The sent queue for TCP sockets",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sockstat_sent_queue_bytes{protocol=\"tcp\"} > bool 0",
     "legendFormat": "{{process_name}}_{{pid}}_{{fd}}"
    }
   ]
  },
  {
   "title": "UDP sent queue",
   "type": "timeseries",
   "description": "The sent queue for UDP sockets",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sockstat_sent_queue_bytes{protocol=\"udp\"} > bool 0",
     "legendFormat": "{{process_name}}_{{pid}}_{{fd}}"
    }
   ]
  },
  {
   "title": "TCP receive queue",
   "type": "timeseries",
   "description": "The receive queue for TCP sockets",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sockstat_receive_queue_bytes{protocol=\"tcp\"}",
     "legendFormat": "{{process_name}}_{{pid}}_{{fd}}"
    }
   ]
  },
  {
   "title": "UDP receive queue",
   "type": "timeseries",
   "description": "The receive queue for UDP sockets",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sockstat_receive_queue_bytes{protocol=\"udp\"}",
     "legendFormat": "{{process_name}}_{{pid}}_{{fd}}"
    }
   ]
  },
  {
   "title": "TCP retransmission count",
   "type": "timeseries",
   "description": "Number of TCP packets for which retransmissions was attempted",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sockstat_retransmissions_total{protocol=\"tcp\"}",
     "legendFormat": "{{process_name}}_{{pid}}_{{fd}}"
    }
   ]
  },
  {
   "title": "UDP retransmission count",
   "type": "timeseries",
   "description": "The number of UDP packets for which retransmission occured",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sockstat_retransmissions_total{protocol=\"udp\"}",
     "legendFormat": "{{process_name}}_{{pid}}_{{fd}}"
    }
   ]
  }
 ]
}